name: Build TWRP for Samsung A36 (a36xq)

on:
  workflow_dispatch:
    inputs:
      manifest_branch:
        description: "TWRP Manifest Branch"
        required: true
        default: "twrp-14.1"

      device_tree:
        description: "Device Tree URL"
        required: true
        default: "https://github.com/twrpdtgen/android_device_samsung_a36xq"

      device_tree_branch:
        description: "Device Tree Branch"
        required: true
        default: "android-12.1"

      device_path:
        description: "Device Path"
        required: true
        default: "device/samsung/a36xq"

      device_codename:
        description: "Device Codename"
        required: true
        default: "a36xq"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: ðŸ“¦ Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git-core gnupg flex bison build-essential zip curl \
            zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            libncurses5-dev x11proto-core-dev libx11-dev libgl1-mesa-dev \
            libxml2-utils xsltproc unzip fontconfig bc ccache \
            libssl-dev python3 python-is-python3

      - name: ðŸ”§ Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: ðŸ“¥ Init TWRP manifest
        run: |
